@EmployeeAPI_HostAddress = http://localhost:5115

GET https://localhost:7194/api/employee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjYiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiUmFodWwgU2hhcm1hIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoidXNlcjFAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzg0ODg5NTA5LCJpc3MiOiJFbXBsb3llZUFQSSIsImF1ZCI6IkVtcGxveWVlQVBJIn0.vvCn_t3OK1PuElN0C91hxx9QkpKwnSfO3Di0G2n7AbY
Accept: application/json

### Add Employee
POST https://localhost:7194/api/employee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiSFIgVXNlciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImhyQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiSFIiLCJleHAiOjE3ODQ4ODY0NzgsImlzcyI6IkVtcGxveWVlQVBJIiwiYXVkIjoiRW1wbG95ZWVBUEkifQ.Iwdljw1C_tk7rsL9P_x19WQWewSicJsWzaKW6RsAFSs
Content-Type: application/json
Accept: application/json
{
  "firstName": "Rahul",
  "lastName": "Sharma",
  "email":"rahul@example.com",
  "phone": "9876543213",
  "department": "Sales",
  "salary": 95000,
  "dateOfJoining": "2026-07-22"
}

### Update Employee

PUT https://localhost:7194/api/employee/13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiSFIgVXNlciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImhyQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiSFIiLCJleHAiOjE3ODQ4ODY0NzgsImlzcyI6IkVtcGxveWVlQVBJIiwiYXVkIjoiRW1wbG95ZWVBUEkifQ.Iwdljw1C_tk7rsL9P_x19WQWewSicJsWzaKW6RsAFSs
Content-Type: application/json

{
  "firstName": "Rahul",
  "lastName": "Patil",
  "email": "rahul@gmail.com",
  "phone": "9876543210",
  "department": "Sales",
  "salary": 95000,
  "dateOfJoining": "2026-07-22"
}

### Delete Employee

DELETE https://localhost:7194/api/employee/6
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiSFIgVXNlciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImhyQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiSFIiLCJleHAiOjE3ODQ4ODY0NzgsImlzcyI6IkVtcGxveWVlQVBJIiwiYXVkIjoiRW1wbG95ZWVBUEkifQ.Iwdljw1C_tk7rsL9P_x19WQWewSicJsWzaKW6RsAFSs
Accept: application/json